/**
 * API controllers and methods menu
 */
export const apiMenu = [
    {
        id: 'state',
        type: 'group',
        title: 'Common',
        items: [
            { title: 'Read state', id: 'readStateForm' },
            { title: 'Main state', id: 'mainStateForm' },
            { title: 'DB version', id: 'dbVersionForm' },
        ],
    },
    {
        id: 'account',
        type: 'group',
        title: 'Accounts',
        items: [
            { title: 'List', id: 'listAccForm' },
            { title: 'Read', id: 'readAccForm' },
            { title: 'Create', id: 'createAccForm' },
            { title: 'Update', id: 'updateAccForm' },
            { title: 'Show', id: 'showAccForm' },
            { title: 'Hide', id: 'hideAccForm' },
            { title: 'Delete', id: 'delAccForm' },
            { title: 'Set position', id: 'setAccPosForm' },
        ],
    },
    {
        id: 'person',
        type: 'group',
        title: 'Persons',
        items: [
            { title: 'List', id: 'listPersonsForm' },
            { title: 'Read', id: 'readPersonForm' },
            { title: 'Create', id: 'createPersonForm' },
            { title: 'Update', id: 'updatePersonForm' },
            { title: 'Show', id: 'showPersonForm' },
            { title: 'Hide', id: 'hidePersonForm' },
            { title: 'Delete', id: 'delPersonForm' },
            { title: 'Set position', id: 'setPersonPosForm' },
        ],
    },
    {
        id: 'transaction',
        type: 'group',
        title: 'Transactions',
        items: [
            { title: 'List', id: 'listTrForm' },
            { title: 'Read', id: 'readTrForm' },
            { title: 'Create', id: 'createTrForm' },
            { title: 'Create debt', id: 'createDebtForm' },
            { title: 'Update', id: 'updateTrForm' },
            { title: 'Update debt', id: 'updateDebtForm' },
            { title: 'Delete', id: 'delTrForm' },
            { title: 'Set category', id: 'setTrCategoryForm' },
            { title: 'Set position', id: 'setTrPosForm' },
            { title: 'Statistics', id: 'statisticsForm' },
        ],
    },
    {
        id: 'schedule',
        type: 'group',
        title: 'Schedule',
        items: [
            { title: 'List', id: 'listScheduledTrForm' },
            { title: 'Read', id: 'readScheduledTrForm' },
            { title: 'Create', id: 'createScheduledTrForm' },
            { title: 'Create debt', id: 'createScheduledDebtForm' },
            { title: 'Update', id: 'updateScheduledTrForm' },
            { title: 'Update debt', id: 'updateScheduledDebtForm' },
            { title: 'Delete', id: 'delScheduledTrForm' },
            { title: 'Finish', id: 'finishScheduledTrForm' },
        ],
    },
    {
        id: 'reminder',
        type: 'group',
        title: 'Reminders',
        items: [
            { title: 'List', id: 'listReminderForm' },
            { title: 'Read', id: 'readReminderForm' },
            { title: 'Upcoming', id: 'upcomingRemindersForm' },
            { title: 'Confirm', id: 'confirmReminderForm' },
            { title: 'Cancel', id: 'cancelReminderForm' },
        ],
    },
    {
        id: 'category',
        type: 'group',
        title: 'Categories',
        items: [
            { title: 'List', id: 'listCategoriesForm' },
            { title: 'Read', id: 'readCategoryForm' },
            { title: 'Create', id: 'createCategoryForm' },
            { title: 'Update', id: 'updateCategoryForm' },
            { title: 'Delete', id: 'delCategoryForm' },
            { title: 'Set position', id: 'setCategoryPosForm' },
        ],
    },
    {
        id: 'importtpl',
        type: 'group',
        title: 'Import templates',
        items: [
            { title: 'List', id: 'listTplForm' },
            { title: 'Read', id: 'readTplForm' },
            { title: 'Create', id: 'createTplForm' },
            { title: 'Update', id: 'updateTplForm' },
            { title: 'Delete', id: 'delTplForm' },
        ],
    },
    {
        id: 'importrule',
        type: 'group',
        title: 'Import rules',
        items: [
            { title: 'List', id: 'listRuleForm' },
            { title: 'Read', id: 'readRuleForm' },
            { title: 'Create', id: 'createRuleForm' },
            { title: 'Update', id: 'updateRuleForm' },
            { title: 'Delete', id: 'delRuleForm' },
        ],
    },
    {
        id: 'importcond',
        type: 'group',
        title: 'Import conditions',
        items: [
            { title: 'List', id: 'listCondForm' },
            { title: 'Read', id: 'readCondForm' },
            { title: 'Create', id: 'createCondForm' },
            { title: 'Update', id: 'updateCondForm' },
            { title: 'Delete', id: 'delCondForm' },
        ],
    },
    {
        id: 'importaction',
        type: 'group',
        title: 'Import actions',
        items: [
            { title: 'List', id: 'listActForm' },
            { title: 'Read', id: 'readActForm' },
            { title: 'Create', id: 'createActForm' },
            { title: 'Update', id: 'updateActForm' },
            { title: 'Delete', id: 'delActForm' },
        ],
    },
    {
        id: 'currency',
        type: 'group',
        title: 'Currency',
        items: [
            { title: 'List', id: 'listCurrForm' },
            { title: 'Read', id: 'readCurrForm' },
            { title: 'Create', id: 'createCurrForm' },
            { title: 'Update', id: 'updateCurrForm' },
            { title: 'Delete', id: 'delCurrForm' },
        ],
    },
    {
        id: 'usercurrency',
        type: 'group',
        title: 'User currency',
        items: [
            { title: 'List', id: 'listUserCurrencyForm' },
            { title: 'Read', id: 'readUserCurrencyForm' },
            { title: 'Create', id: 'createUserCurrencyForm' },
            { title: 'Update', id: 'updateUserCurrencyForm' },
            { title: 'Delete', id: 'delUserCurrencyForm' },
            { title: 'Set position', id: 'setUserCurrencyPosForm' },
        ],
    },
    {
        id: 'color',
        type: 'group',
        title: 'Color',
        items: [
            { title: 'List', id: 'listColorForm' },
            { title: 'Read', id: 'readColorForm' },
            { title: 'Create', id: 'createColorForm' },
            { title: 'Update', id: 'updateColorForm' },
            { title: 'Delete', id: 'delColorForm' },
        ],
    },
    {
        id: 'icon',
        type: 'group',
        title: 'Icon',
        items: [
            { title: 'List', id: 'listIconForm' },
            { title: 'Read', id: 'readIconForm' },
            { title: 'Create', id: 'createIconForm' },
            { title: 'Update', id: 'updateIconForm' },
            { title: 'Delete', id: 'delIconForm' },
        ],
    },
    {
        id: 'user',
        type: 'group',
        title: 'User',
        items: [
            { title: 'Login', id: 'loginForm' },
            { title: 'Logout', id: 'logoutForm' },
            { title: 'Register', id: 'registerForm' },
        ],
    },
    {
        id: 'profile',
        type: 'group',
        title: 'Profile',
        items: [
            { title: 'Read profile', id: 'readProfileForm' },
            { title: 'Change name', id: 'changeNameForm' },
            { title: 'Change password', id: 'changePwdForm' },
            { title: 'Update settings', id: 'updateSettingsForm' },
            { title: 'Reset data', id: 'resetForm' },
        ],
    },
];
